name: Pipeline
on: [push]
jobs:
  build-and-check:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    environment: github-pages
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v3

      - name: Install
        run: |
          npm ci --force
        env:
          CI: ""

      - name: Code Linting
        run: |
          npm run lint
        env:
          CI: ""

      - name: Code Testing
        run: |
          npm run test
        env:
          CI: ""
